### ISSUE TITLE
Unable to build the package

### ISSUE THREAD

**Issue by sunilbindra** [Merck/sonar-r-plugin#13]
Hi
I am trying to add R Plugin package in Sonar Qube. I have installed HJDK Java 11 on the server as well. When I try to build plugin using ./mvnw clean package. It fails with Java error. Any Idea. I tried to copy the certificates as well from Java 11 to already installed Java 8. Belwo is the error:-

C:\temp\sonar-r-plugin-master>mvnw.cmd clean package
Exception in thread "main" javax.net.ssl.SSLHandshakeException: sun.security.val
idator.ValidatorException: PKIX path building failed: sun.security.provider.cert
path.SunCertPathBuilderException: unable to find valid certification path to req
uested target
        at sun.security.ssl.Alerts.getSSLException(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
        at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
        at sun.security.ssl.Handshaker.processLoop(Unknown Source)
        at sun.security.ssl.Handshaker.process_record(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source
)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect
(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown S
ource)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown So
urce)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unkn
own Source)
        at org.apache.maven.wrapper.DefaultDownloader.downloadInternal(DefaultDo
wnloader.java:90)
        at org.apache.maven.wrapper.DefaultDownloader.download(DefaultDownloader
.java:76)
        at org.apache.maven.wrapper.Installer.createDist(Installer.java:72)
        at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java
:121)
        at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:
61)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed:
 sun.security.provider.certpath.SunCertPathBuilderException: unable to find vali
d certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
        at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
        at sun.security.validator.Validator.validate(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Sour
ce)
        ... 18 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to
 find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Sourc
e)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown
 Source)
        at java.security.cert.CertPathBuilder.build(Unknown Source)
        ... 24 more

C:\temp\sonar-r-plugin-master>%JAVA_HOME%
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

C:\temp\sonar-r-plugin-master>

Thanks

**Comment by kmoco2am** [comment]
mvnw is a wrapper around Maven and it tries to download it from internet. And the error you have is about checking SSL, probably HTTPS of Maven site. Check your HTTP proxy configuration if you have any.
